name: Trello-clone
services:
  frontend:
    container_name: angular_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    container_name: go_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: trello_clone
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
       POSTGRES_USER: user
       POSTGRES_PASSWORD: password
       POSTGRES_DB: trello_clone
       POSTGRES_HOST: 0.0.0.0
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8081:80"
    depends_on:
      - db
volumes:
  postgres_data: